account/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from .forms import LoginForm
from .views import logout_view

app_name = 'account'


urlpatterns = [
    path('login/', LoginView.as_view(template_name='account/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', logout_view, name='logout'),
]

chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'


urlpatterns = [
    path('api/create-room/<str:uuid>/', views.create_room, name='create-room'),
    path('chat-admin/', views.admin, name='admin'),
    path('chat-admin/add-user/', views.add_user, name='add_user'),
    path('remove_user/<uuid:user_id>', views.remove_user, name='remove_user'),
    path('chat-admin/users/<uuid:uuid>/', views.user_detail, name='user_detail'),
    path('chat-admin/users/<uuid:uuid>/edit/', views.edit_user, name='edit_user'),
    path('chat-admin/<str:uuid>/', views.room, name='room'),
    path('chat-admin/<str:uuid>/delete/', views.delete_room, name='delete_room'),
]

core/urls.py
from django.urls import path

from . import views

app_name = 'core'


urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
]

jatte/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('core.urls')),
    path('', include('chat.urls')),
    path('', include('account.urls')),
    path('admin/', admin.site.urls),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'core/index.html')


def about(request):
    return render(request, 'core/about.html')

core/templates/core/about.html
{% extends 'core/base.html' %}

{% load static %}

{% block content %}
<div class="flex flex-col items-center justify-center">
  <h1 class="mb-6 text-4xl font-bold text-rose-600">Welcome to Our Chatterbox bot</h1>

  <div class="max-w-md mx-auto bg-white p-6 rounded-lg shadow-lg">
    <p class="text-gray-700 leading-relaxed">
      Our Chatterbox bot is designed to provide you with quick and helpful information. Whether you have questions about our
      products, need assistance, or just want to chat, our chatbot is here for you.
    </p>

    <p class="mt-4 text-gray-700 leading-relaxed">
      Powered by cutting-edge artificial intelligence, our chatbot strives to understand your queries and provide
      relevant responses. Feel free to explore and engage with our Chatterbox bot for a seamless experience.
    </p>

    <p class="mt-4 text-gray-700 leading-relaxed">
      Your satisfaction is our priority, and our Chatterbox bot is ready to assist you 24/7. If you have any feedback or
      suggestions, please let us know. We're constantly working to improve your interaction with our chatbot.
    </p>
  </div>

  <div class="mt-8">
    <h2 class="text-2xl font-bold text-rose-600">Meet Our Team</h2>
    <div class="flex space-x-4 mt-4">
      <!-- Add team member cards with images, names, and roles -->
      <div class="flex-shrink-0 w-20 h-20">
        <img src="{% static 'images/my-profile-pic.png' %}" alt="Team Member 1" class="w-full h-full object-cover rounded-full">
      </div>
      <div class="flex-shrink-0 w-20 h-20">
        <img src="{% static 'images/team-member-2.png' %}" alt="Team Member 2" class="w-full h-full object-cover rounded-full">
      </div>
      <div class="flex-shrink-0 w-20 h-20">
        <img src="{% static 'images/team-member-3.png' %}" alt="Team Member 3" class="w-full h-full object-cover rounded-full">
      </div>
    </div>
  </div>
</div>
{% endblock %}

core/templates/core/base.html
{% load static %}

<!doctype html>

<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link rel="stylesheet" type="text/css" href="{% static 'css/main.min.css' %}">
    </head>

    <body>
        <div class="p-2">
            <nav class="p-6 bg-rose-600 text-white flex justify-between items-center rounded-xl">
                <a href="{% url 'core:index' %}" class="text-xl">Chatterbox</a>

                <div class="flex items-center space-x-4">
                    <a href="{% url 'core:index' %}">Home</a>
                    <a href="{% url 'core:about' %}">About</a>
                
                    {% if request.user.is_authenticated %}
                    <a href="{% url 'account:logout' %}">Logout</a>
                    <a href="{% url 'chat:admin' %}" class="inline-block py-4 px-6 bg-rose-800 text-white rounded-xl">Chat admin</a>
                    {% else %}
                    <a href="{% url 'account:login' %}">Login</a>
                    {% endif %}
                </div>

            </nav>

            <main class="max-w-6xl mx-auto p-6">
                {% if messages %}
                    <div class="message mb-6 p-6 bg-gray-800 text-white rounded-xl">
                        {% for message in messages %}
                            <p>{{ message }}</p>
                        {% endfor %}
                    </div>
                {% endif %}

                {% block content %}
                {% endblock %}
            </main>
        </div>

        <footer class="py-12 px-6 bg-gray-800 text-white text-center text-xs">
            <p>Copyright (c) 2023 - Chatterbox</p>
        </footer>

        {% block scripts %}
        {% endblock %}
    </body>
</html>

core/templates/core/index.html
{% extends 'core/base.html' %}

{% load static %}

{% block content %}
    <div class="mt-12 py-12 px-8 grid grid-cols-5 gap-4 items-center border border-rose-200 rounded-xl">
        <div class="col-span-2">
            <img src="{% static 'images/header.png' %}" alt="header-img">
        </div>

        <div class="col-span-3">
            <h1 class="mb-8 text-3xl">Welcome to Chatterbox</h1>

            <h2 class="text-lg text-gray-500">Connect with us, share experiences, and chat in real-time. Chatterbox is your go-to platform for meaningful
            conversations and staying connected with our latest updates.</h2>
        </div>
    </div>

    <div class="mt-12 py-12 px-8 grid grid-cols-3 gap-4 items-center">
        <div class="text-center">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-12 h-12 mb-8 text-rose-600 mx-auto">
                <path stroke-linecap="round" stroke-linejoin="round" d="M8.625 9.75a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H8.25m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H12m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0h-.375m-13.5 3.01c0 1.6 1.123 2.994 2.707 3.227 1.087.16 2.185.283 3.293.369V21l4.184-4.183a1.14 1.14 0 01.778-.332 48.294 48.294 0 005.83-.498c1.585-.233 2.708-1.626 2.708-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z" />
            </svg>  
            
            <h3 class="mb-4 text-xl text-gray-800">Support Chat</h3>

            <p class="text-gray-500">Hi there! How can we help you today?</p> 
        </div>

        <div class="text-center">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-12 h-12 mb-8 text-rose-600 mx-auto">
                <path stroke-linecap="round" stroke-linejoin="round" d="M8.625 9.75a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H8.25m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H12m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0h-.375m-13.5 3.01c0 1.6 1.123 2.994 2.707 3.227 1.087.16 2.185.283 3.293.369V21l4.184-4.183a1.14 1.14 0 01.778-.332 48.294 48.294 0 005.83-.498c1.585-.233 2.708-1.626 2.708-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z" />
            </svg>  
            
            <h3 class="mb-4 text-xl text-gray-800">Friend Chat</h3>

            <p class="text-gray-500">Hey! Did you watch the latest episode of that show?</p> 
        </div>

        <div class="text-center">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-12 h-12 mb-8 text-rose-600 mx-auto">
                <path stroke-linecap="round" stroke-linejoin="round" d="M8.625 9.75a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H8.25m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H12m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0h-.375m-13.5 3.01c0 1.6 1.123 2.994 2.707 3.227 1.087.16 2.185.283 3.293.369V21l4.184-4.183a1.14 1.14 0 01.778-.332 48.294 48.294 0 005.83-.498c1.585-.233 2.708-1.626 2.708-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z" />
            </svg>  
            
            <h3 class="mb-4 text-xl text-gray-800">Family Chat</h3>

            <p class="text-gray-500">Hi everyone! Just checking in. How's everyone doing?</p> 
        </div>

        <div class="text-center">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-12 h-12 mb-8 text-rose-600 mx-auto">
                <path stroke-linecap="round" stroke-linejoin="round" d="M8.625 9.75a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H8.25m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H12m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0h-.375m-13.5 3.01c0 1.6 1.123 2.994 2.707 3.227 1.087.16 2.185.283 3.293.369V21l4.184-4.183a1.14 1.14 0 01.778-.332 48.294 48.294 0 005.83-.498c1.585-.233 2.708-1.626 2.708-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z" />
            </svg>  
            
            <h3 class="mb-4 text-xl text-gray-800">Project Team Chat</h3>

            <p class="text-gray-500">Quick update: We'll be having a team meeting tomorrow at 2 PM.</p> 
        </div>

        <div class="text-center">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-12 h-12 mb-8 text-rose-600 mx-auto">
                <path stroke-linecap="round" stroke-linejoin="round" d="M8.625 9.75a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H8.25m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H12m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0h-.375m-13.5 3.01c0 1.6 1.123 2.994 2.707 3.227 1.087.16 2.185.283 3.293.369V21l4.184-4.183a1.14 1.14 0 01.778-.332 48.294 48.294 0 005.83-.498c1.585-.233 2.708-1.626 2.708-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z" />
            </svg>  
            
            <h3 class="mb-4 text-xl text-gray-800">Travel Enthusiasts Chat</h3>

            <p class="text-gray-500">Share your favorite travel destinations! ✈️</p> 
        </div>

        <div class="text-center">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-12 h-12 mb-8 text-rose-600 mx-auto">
                <path stroke-linecap="round" stroke-linejoin="round" d="M8.625 9.75a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H8.25m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H12m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0h-.375m-13.5 3.01c0 1.6 1.123 2.994 2.707 3.227 1.087.16 2.185.283 3.293.369V21l4.184-4.183a1.14 1.14 0 01.778-.332 48.294 48.294 0 005.83-.498c1.585-.233 2.708-1.626 2.708-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z" />
            </svg>  
            
            <h3 class="mb-4 text-xl text-gray-800">Tech Enthusiasts Chat</h3>

            <p class="text-gray-500">Any recommendations for a good coding playlist?</p> 
        </div>
    </div>

    {% include 'chat/partials/chat_bubble.html' %}
{% endblock %}

{% block scripts %}
    <script src="{% static 'js/main.js' %}"></script>
{% endblock %}